# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-03 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20181103_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshiptype',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
