# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-03 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_relationshiptype_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshiptype',
            name='color',
            field=models.CharField(default='004d80', max_length=6),
        ),
    ]
