# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-04 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_relationshiptype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshiptype',
            name='display',
            field=models.IntegerField(default=1),
        ),
    ]
