# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-04 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_relationshiptype_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='show_in_legend',
            field=models.IntegerField(default=1),
        ),
    ]
