# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-06 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_house_show_in_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='major_house',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1),
        ),
        migrations.AlterField(
            model_name='edge',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='graph.RelationshipType'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source', to='graph.Person'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target', to='graph.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='alive',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='house',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='graph.House'),
        ),
    ]
